
install-dbeaver:
  sources_list_name: dbeaver.list
  sources_list_contents: deb https://dbeaver.io/debs/dbeaver-ce /
  key_url: https://dbeaver.io/debs/dbeaver.gpg.key
  key_file_name: dbeaver.gpg
  package: dbeaver-ce

install-cert:
  ca_cert_dir: /usr/local/share/ca-certificates
  ca_certs_bundle_path: /etc/ssl/certs/ca-certificates.crt

install-chrome:
  repo_file_template: deb [arch=${architecture}] http://dl.google.com/linux/chrome/deb/ stable main
  repo_file_name: google-chrome.list
  key_url: https://dl.google.com/linux/linux_signing_key.pub
  key_file_name: google-chrome.gpg
  package: google-chrome-stable

install-docker:
  repo_file_template: deb [arch=${architecture}] https://download.docker.com/linux/debian ${release} stable
  repo_file_name: docker.list
  key_url: https://download.docker.com/linux/debian/gpg
  key_file_name: docker.gpg
  packages: [docker-ce, docker-ce-cli, containerd.io]
  os_name: linux

install-packages:
  packages:
    - debsig-verify
    - bind9-dnsutils
    - bridge-utils
    - flameshot
    - gimp
    - git-gui
    - gitk
    - gnupg
    - jq
    - netcat
    - net-tools
    - okular
    - rsync
    - terminator
    - tree
    - yadm
    # All of the packages from the bootstrap
    - apt-transport-https
    - build-essential
    - curl
    - git
    - libbz2-dev
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - libnss3-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - software-properties-common
    - vim
    - wget
    - zlib1g-dev

install-redshift:
  packages:
    - redshift

install-slack:
  download_url_prefix: https://downloads.slack-edge.com/releases/linux/4.29.149/prod/x64
  package: slack-desktop-4.29.149-amd64.deb
  verification:
    public_key_url: https://slack.com/gpg/slack_pubkey_20220708.gpg
    public_key_filename: slack_pubkey_20220708.gpg
    debsig_keyring_dir: /usr/share/debsig/keyrings/D1EAC4827EB66C16
    debsig_policy_dir: /etc/debsig/policies/D1EAC4827EB66C16
    # debsig_keyring_filename: slack_debsig.gpg
    debsig_policy_filename: slack.pol
    debsig_policy_contents: |
      <?xml version="1.0"?>
      <!DOCTYPE Policy SYSTEM "https://www.debian.org/debsig/1.0/policy.dtd">
      <Policy xmlns="https://www.debian.org/debsig/1.0/">
      <Origin Name="Slack" id="D1EAC4827EB66C16" Description="Slack"/>
      <Selection>
      <Required Type="origin" File="debsig.gpg" id="D1EAC4827EB66C16"/>
      </Selection>
      <Verification>
      <Required Type="origin" File="debsig.gpg" id="D1EAC4827EB66C16"/>
      </Verification>
      </Policy>
